version: '3.4'

services:

  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/raspberrypi4-homeassistant:stable"
    volumes:
      - "${LOCAL_BASE_PATH}/homeassistant:/config"
      - "/etc/localtime:/etc/localtime:ro"
    restart: unless-stopped
    privileged: true
    network_mode: host

  mosquitto:
    container_name: mosquitto
    image: "eclipse-mosquitto"
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - "${LOCAL_BASE_PATH}/mosquitto:/mosquitto"
      - "${LOCAL_BASE_PATH}/mosquitto/data:/mosquitto/data"
      - "${LOCAL_BASE_PATH}/mosquitto/log:/mosquitto/log"
    network_mode: host

  influxdb:
    image: influxdb:2.1.1
    container_name: influxdb
    environment:
      - "DOCKER_INFLUXDB_INIT_MODE=setup"
      - "DOCKER_INFLUXDB_INIT_USERNAME=${DOCKER_INFLUXDB_INIT_USERNAME:-homeassistant}"
      - "DOCKER_INFLUXDB_INIT_PASSWORD=${DOCKER_INFLUXDB_INIT_PASSWORD:-homeassistant}"
      - "DOCKER_INFLUXDB_INIT_ORG=${DOCKER_INFLUXDB_INIT_ORG:-home}"
      - "DOCKER_INFLUXDB_INIT_BUCKET=${DOCKER_INFLUXDB_INIT_BUCKET:-homeassistant}"
    ports:
      - "8086:8086"
    volumes:
      - "${LOCAL_BASE_PATH}/influxdb/data:/var/lib/influxdb2"
      - "${LOCAL_BASE_PATH}/influxdb/config.yml:/etc/influxdb2/config.yml"

  deconz:
    image: deconzcommunity/deconz
    container_name: deconz
    restart: always
    ports: 
      - "8085:80"
      - "4435:443"
    volumes:
      - "${LOCAL_BASE_PATH}/deconz:/opt/deCONZ"
    devices:
      - /dev/ttyUSB0
    environment:
      - TZ=Europe/Berlin
      - DECONZ_WEB_PORT=80
      - DECONZ_WS_PORT=443
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTAU=0
      - DECONZ_DEVICE=/dev/ttyUSB0
      - DECONZ_VNC_MODE=1
      - DECONZ_VNC_PORT=5900
